global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'basilica'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'basilica-validator'
    static_configs:
      - targets: ['160.202.129.15:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 160.202.129.15:9090
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: basilica_validator_.*
        action: keep

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics


remote_write:
  - url: http://localhost:9090/api/v1/write
    write_relabel_configs:
      - source_labels: [__name__]
        regex: basilica_.*
        action: keep

# Storage is configured via command line flags in Docker Compose