blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/tsErZGXX
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://github.com/tplr-ai/basilica/tree/main/docs
    about: Check our documentation for common questions
  - name: Security Issues
    url: https://discord.gg/tsErZGXX
    about: Please report security vulnerabilities via Discord