apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: loki
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      incrementalQueryOverlapWindow: 10m
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - name: TraceID
          matcherRegex: trace_id=(\w+)
          url: http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D
          datasourceUid: jaeger
    secureJsonData: {}

  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1