# Miner Configuration for Local Development

[server]
host = "0.0.0.0"
port = 8092

[database]
url = "sqlite:/tmp/miner.db?mode=rwc"
max_connections = 5
min_connections = 1
connect_timeout = { secs = 5, nanos = 0 }
run_migrations = true

[logging]
level = "info"
format = "pretty"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9091

[bittensor]
wallet_name = "templar_test"
hotkey_name = "M1"
network = "test"
netuid = 387
coldkey_name = "default"
axon_port = 8091
# For test network, endpoint will be auto-detected as wss://test.finney.opentensor.ai:443
# chain_endpoint = "wss://test.finney.opentensor.ai:443"
# Set external IP for axon registration (required by chain validation)
# Using a private network IP that will pass chain validation
# This is only for local development - in production, use your actual external IP
external_ip = "10.0.0.1"
max_weight_uids = 256

[validator_comms]
request_timeout = { secs = 30, nanos = 0 }
max_concurrent_sessions = 100

[validator_comms.auth]
enabled = false  # Disable auth for local testing
method = "bittensor_signature"

[validator_comms.auth.token_validation]
validate_issuer = true
validate_audience = true
validate_expiration = true
clock_skew_tolerance = { secs = 60, nanos = 0 }

[validator_comms.rate_limit]
enabled = false  # Disable rate limiting for local testing
requests_per_second = 10
burst_capacity = 20
window_duration = { secs = 60, nanos = 0 }

[executor_management]
health_check_interval = { secs = 30, nanos = 0 }
health_check_timeout = { secs = 10, nanos = 0 }
max_retry_attempts = 3
auto_recovery = true

# Executors will be managed via remote deployment below
executors = []

# Remote executor deployment configuration
[remote_executor_deployment]
# Path to local executor binary (mounted in container)
local_executor_binary = "/executor-binary"
auto_deploy = false  # Set to true to auto-deploy on startup
auto_start = true
health_check_interval = { secs = 60, nanos = 0 }

# Executor configuration template
executor_config_template = """
[server]
host = "0.0.0.0"
port = {EXECUTOR_PORT}

[database]
url = "sqlite:{DATA_DIR}/executor.db?mode=rwc"
run_migrations = true

[logging]
level = "info"
format = "pretty"

[miner]
managing_miner_hotkey = "{MINER_HOTKEY}"
managing_miner_address = "{MINER_ADDRESS}"

[docker]
socket_path = "/var/run/docker.sock"
enable_gpu_support = true

[validation]
enable_ssh_access = true
"""

# Remote GPU machine configuration
[[remote_executor_deployment.remote_machines]]
id = "gpu-1"
name = "GPU Instance 1"
executor_port = 50051
gpu_count = 1

[remote_executor_deployment.remote_machines.ssh]
host = "72.46.85.229"
port = 22
username = "shadeform"
private_key_path = "/root/.ssh/basilica_gpu_test"
ssh_options = [
    "StrictHostKeyChecking=no",
    "UserKnownHostsFile=/dev/null",
    "ServerAliveInterval=30"  # Keep connection alive
]

[security]
enable_mtls = false
jwt_secret = "dev-secret-change-in-production"
token_expiration = { secs = 3600, nanos = 0 }
allowed_validators = []
verify_signatures = false  # Disabled for development