# Simplified localtest compose file that focuses on test-specific services
# Core services (miner, executor) can be started from docker/docker-compose.dev-sqlite.yml
# This file adds test-specific services on top

services:
  # Validator service (not in main docker compose)
  validator:
    image: basilica/validator:localtest
    container_name: basilica-validator-test
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    network_mode: host  # Use host network to access local subtensor
    volumes:
      - ./validator.toml:/etc/basilica/validator.toml:ro
      - ./keys:/etc/basilica/keys:ro
      - attestor_share:/shared/attestor:ro
      - validator_data:/var/lib/basilica/validator
      - ~/.bittensor:/root/.bittensor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    entrypoint: ["/bin/sh", "-c", "mkdir -p /var/lib/basilica/validator && touch /var/lib/basilica/validator/validator.db && exec /usr/local/bin/basilica-validator start --config /etc/basilica/validator.toml --local-test"]

  # Local Subtensor (blockchain) for testing
  subtensor:
    image: opentensor/subtensor:latest
    container_name: basilica-subtensor
    ports:
      - "9944:9944"  # WebSocket RPC
      - "9933:9933"  # HTTP RPC
      - "30333:30333"  # P2P
    environment:
      CHAIN: local
      RUST_LOG: info
    volumes:
      - subtensor_data:/data
    command: [
      "--dev",
      "--rpc-external",
      "--rpc-cors=all",
      "--rpc-methods=unsafe",
      "--ws-external",
      "--pruning=archive"
    ]
    networks:
      - basilica_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # SSH target for validation testing
  ssh-target:
    image: basilica/ssh-target:localtest
    container_name: basilica-ssh-target
    ports:
      - "2222:22"
    volumes:
      - ./keys/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      - basilica_network
    restart: unless-stopped

  # Database initialization
  db-init:
    image: busybox
    container_name: basilica-db-init
    volumes:
      - validator_data:/validator_data
      - miner_data:/miner_data
      - executor_data:/executor_data
    command: |
      sh -c "
        mkdir -p /validator_data /miner_data /executor_data
        touch /validator_data/validator.db /miner_data/miner.db /executor_data/executor.db
        echo 'Databases initialized'
      "
    networks:
      - basilica_network

volumes:
  validator_data:
  miner_data:
  executor_data:
  subtensor_data:
  attestor_share:

networks:
  basilica_network:
    driver: bridge