# Minimal Basilica API configuration

# Server configuration
[server]
bind_address = "0.0.0.0:8000"

# Bittensor network configuration
[bittensor]
# Network: "finney" for mainnet (Subnet 39) or "test" for testnet (Subnet 387)
network = "test"
netuid = 387
# Explicit chain endpoint for testnet
chain_endpoint = "wss://test.finney.opentensor.ai:443"
validator_hotkey = "5Dvs1D21nUF9GLH67ZF3kMcGwLQEoD4LbMQ9hycGMGvviGCe"  # Replace with actual validator hotkey
discovery_interval = 30
