[bittensor]
wallet_name = "default"
hotkey_name = "h1"
external_ip = "66.172.11.7"
axon_port = 8080
network = "finney"
netuid = 39
weight_interval_secs = 300

[node_management]
nodes = [
  { host = "216.81.248.117", port = 22, username = "ubuntu" },
]

[validator_comms]
host = "0.0.0.0"
port = 8080

[ssh_session]
miner_node_key_path = "~/.ssh/miner_node_key"

[validator_assignment]
enabled = true
strategy = "highest_stake"
min_stake_threshold = 12000.0
validator_hotkey = "5G3qVaXzKMPDm5AJ3dpzbpUC27kpccBvDwzSWXrq8M6qMmbC"