[database]
url = "sqlite:/opt/basilica/data/validator.db?mode=rwc"
max_connections = 10
run_migrations = true

[server]
host = "0.0.0.0"
port = 8080
advertised_host = "160.202.129.15"
advertised_port = 8080
advertised_tls = false
max_connections = 1000
request_timeout = { secs = 30 }

[bittensor]
wallet_name = "basilica"
hotkey_name = "default"
network = "finney"
netuid = 39
chain_endpoint = "wss://entrypoint-finney.opentensor.ai:443"
weight_interval_secs = 300
axon_port = 8080
external_ip = "160.202.129.15"

[verification]
max_concurrent_verifications = 50
min_score_threshold = 0.1
verification_interval = { secs = 600 }
challenge_timeout = { secs = 120 }
retry_attempts = 3
retry_delay = { secs = 5 }
netuid = 39
use_dynamic_discovery = true
discovery_timeout = { secs = 30 }
fallback_to_static = true
cache_miner_info_ttl = { secs = 300 }

[verification.binary_validation]
enabled = true
validator_binary_path = "/opt/basilica/bin/validator-binary"
executor_binary_path = "/opt/basilica/bin/executor-binary"
execution_timeout_secs = 540
output_format = "json"

[metrics]
enabled = true
retention_period = { secs = 604800 }
collection_interval = { secs = 30 }

[metrics.prometheus]
host = "0.0.0.0"
port = 9090
path = "/metrics"

[logging]
level = "debug"
format = "json"
output = "./validator.log"
max_file_size = 104857600
max_files = 10

[api]
enabled = true
swagger_enabled = true
cors_enabled = true
cors_origins = ["*"]
rate_limit = 100

[storage]
data_dir = "/opt/basilica/data"

[ssh_session]
ssh_key_directory = "/opt/basilica/data/ssh_keys"
key_algorithm = "ed25519"
default_session_duration = 300
max_session_duration = 3600
rental_session_duration = 3600
key_cleanup_interval = { secs = 60, nanos = 0 }
enable_automated_sessions = true
max_concurrent_sessions = 5
session_rate_limit = 20
enable_audit_logging = true
audit_log_path = "/opt/basilica/data/ssh_audit.log"
ssh_connection_timeout = { secs = 30, nanos = 0 }
ssh_command_timeout = { secs = 60, nanos = 0 }
ssh_retry_attempts = 3
ssh_retry_delay = { secs = 2, nanos = 0 }

[emission]
# Percentage of total emissions to burn (0.0-100.0)
burn_percentage = 95.0

# UID to receive burn allocation
burn_uid = 204

# Blocks between weight setting operations
# 360 blocks = ~1 hour on Bittensor (12 seconds per block)
weight_set_interval_blocks = 360

# Minimum number of miners required
# per GPU category to receive allocation
min_miners_per_category = 1

# Version key for weight setting operations
# This prevents replay attacks by incrementing with each weight set
weight_version_key = 0

# GPU model allocation percentages
# These percentages determine how emissions
# are distributed across GPU categories
# Must sum to exactly 100.0
[emission.gpu_allocations]
"H100" = 40.0
"H200" = 60.0
