{
 "title": "Basilica Validator Logs",
 "tags": [
  "basilica",
  "validator",
  "logs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "validator_uid", "label": "Validator UID", "query": "204" },
   { "name": "netuid", "label": "Net UID", "query": "39" },
   { "name": "search_text", "label": "Search Text" },
   { "name": "log_level", "label": "Log Level", "query": "debug,info,warn,error" }
  ]
 },
 "panels": [
  {
   "title": "Total Validated GPUs in Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (executor_id, gpu_model) (basilica_validator_executor_gpu_count))",
     "legendFormat": "Total GPUs"
    }
   ]
  },
  {
   "title": "GPUs by Type/Model",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (gpu_model) (count by (executor_id, gpu_model) (basilica_validator_executor_gpu_count))",
     "legendFormat": "{{gpu_model}}"
    }
   ]
  },
  {
   "title": "GPUs per Miner by Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by (miner_uid, gpu_profile) (count by (miner_uid, gpu_profile, executor_id) (basilica_validator_miner_gpu_profiles))"
    }
   ]
  },
  {
   "title": "GPUs per Executor (with Miner)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "max by (executor_id, gpu_model, miner_uid) (basilica_validator_executor_gpu_count)"
    }
   ]
  },
  {
   "title": "Successful Validations per miner",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(500, max by (miner_uid) (basilica_validator_miner_successful_validations))",
     "legendFormat": "Miner {{miner_uid}}"
    }
   ]
  },
  {
   "title": "Miners by Weight",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(500, max by (miner_uid) (basilica_validator_miner_weight{miner_uid!=\"204\"}))\r\n",
     "legendFormat": "Miner {{miner_uid}}"
    }
   ]
  },
  {
   "title": "Log Count per Validator UID per Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "sum by(validator_uid, level) (rate({source=\"docker\", netuid=\"$netuid\"} |= `` | logfmt | __error__ = \"\" [1m]))"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 49, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{source=\"docker\", netuid=\"$netuid\", validator_uid=\"$validator_uid\"} |= `` |~ `$search_text` | logfmt"
    }
   ]
  }
 ]
}