services:
  # PostgreSQL for production-like environment
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api_dev_password
      POSTGRES_DB: basilica_api
    ports:
      - "5432:5432"
    volumes:
      - api_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api -d basilica_api"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - basilica_network_dev

  basilica-api:
    build:
      context: ../..
      dockerfile: scripts/api/Dockerfile
    container_name: basilica-api-dev
    restart: unless-stopped
    
    environment:
      - RUST_LOG='basilica_api=debug'
      - RUST_BACKTRACE=1
      - BASILICA_API_DATABASE__URL=postgres://api:api_dev_password@postgres:5432/basilica_api
    
    volumes:
      - ./dummy_wallet:/home/basilica/.bittensor:ro
      - ../../config/api.toml:/app/api.toml:ro
      - ../../crates:/app/crates:ro
      - ../../Cargo.toml:/app/Cargo.toml:ro
      - ../../Cargo.lock:/app/Cargo.lock:ro
    
    ports:
      - "8000:8000"    # HTTP API
    
    networks:
      - basilica_network_dev
    
    depends_on:
      postgres:
        condition: service_healthy
    
    command: ["--config", "/app/api.toml"]
    

networks:
  basilica_network_dev:
    driver: bridge

volumes:
  api_postgres_data:
    driver: local
