services:
  executor:
    image: ghcr.io/tplr-ai/basilica/executor:latest
    container_name: basilica-executor
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    privileged: true

    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/basilica/config/executor.toml:/opt/basilica/config/executor.toml:ro
      - /opt/basilica/data:/opt/basilica/data:rw
      - ~/.ssh:/opt/basilica/keys:ro
      - /var/log/basilica:/var/log/basilica:rw

    ports:
      - "50051:50051"   # gRPC server (from config server.port)
      - "50052:50052"   # Health port (from config health.port)
      - "9090:9090"     # Metrics port (from config metrics.prometheus.port)
      - "22:22"         # SSH for validator (from config validator.ssh_port)

    dns:
      - 1.1.1.1
      - 1.0.0.1

    networks:
      - basilica_network

    command: ["--server", "--config", "/opt/basilica/config/executor.toml"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50052/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  watchtower:
    image: containrrr/watchtower
    container_name: basilica-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
    dns:
      - 1.1.1.1
      - 1.0.0.1
    command: --label-enable --cleanup --interval 60

networks:
  basilica_network:
    driver: bridge
